name = "glogg"
version = "1.2.0"
description = "A simple, structured JSON logging library for Gleam that works across Erlang and JavaScript targets."
licenses = ["MIT"]
repository = { type = "github", user = "webermarci", repo = "glogg" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
logger_formatter_json = ">= 0.8.4 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
