name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [erlang, javascript]

    steps:
      - uses: actions/checkout@v5

      - uses: erlef/setup-beam@v1.18.2
        with:
          otp-version: "27.3.3"
          gleam-version: "1.12.0"
          rebar3-version: "3"

      - uses: actions/setup-node@v5
        if: matrix.target == 'javascript'
        with:
          node-version: "24"

      - run: gleam deps download

      - name: Run tests
        run: gleam test --target ${{ matrix.target }}

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: erlef/setup-beam@v1.18.2
        with:
          otp-version: "27.3.3"
          gleam-version: "1.12.0"
          rebar3-version: "3"
      - run: gleam format --check src test
